### ISSUE TITLE
Can i use Mysql.data.dll to connect database in Android ?

### ISSUE THREAD

**Issue by ahhoh1011** [Uncle-Uee/MySQL-Unity#3]
Can i use Mysql.data.dll to connect database in Android ?

**Comment by Uncle-Uee** [comment]
Probably not buddy. You most probably want to look at using a JDBC driver for Android.
But you can try and see if it works and let us know.

Alternatively, you can use a REST API to connect to the Database if you are hosting the MySQL Database on Azure for example, or you can use SQLite,
